function RatesCalc

% Takes input earthquake and eruption databases and calculates yearly rates
% for given parameters. Can also generates monte carlo simulations,
% randomising either the earthquake dates, eruption dates, or both. The
% output .mat file generated by this script can be used in RatesPlot.m for
% visualisation


% INPUT

DB_inpeqs='gCMTall2.xlsx'; % Input earthquake database
DB_inperups='GVPall2.xls'; % Input eruption database

start_date='01/01/1976'; % Database start date (dd/mm/yyyy)
end_date='01/01/2021'; % Database end date (dd/mm/yyyy) (=day after last day of records)

output_name='rates_test.mat'; % Output .mat file name for use in RatesPlot.m

lonlims=[-180 180]; % Study area longitutude ([min max] or [polygon vertices]) (-180 to 180) (minimum='left' side of area, maximum='right' side of area)
latlims=[-90 90]; % Study are latitude ([min max] or [polygon vertices]) (-90 to 90)

minEQ=7; % Minimum Mw of earthquake
maxEQ=10; % Maximum Mw of earthquake
mindepth=0; % Minimum earthquake depth (km)
maxdepth=9999; % Maximum earthquake depth (km)
sliptype='all'; % Earthquake type ('all' 'reverse' 'strike-slip' 'normal' 'oblique-reverse' 'oblique-normal')
fashockcheck=0; % Leave as 0 for this code
fashockdist=0; % Leave as 0 for this code

minVEI=2; % Minimum VEI of eruption
vmode='N'; % Method of counting eruptions ('N' = eruptions per year, 'A' = scale VEI by number, 'E' = scale VEI exponentially) 
mult_erups='Y'; % Multiple eruptions from 1 volcano allowed each year? ('Y' or 'N') 
uncert_erups='Y'; % Uncertain start year eruptions ('N' = exclude uncertain start day eruptions, 'Y' = include certain start year eruptions, 'A' = include all eruptions) 

monte_carlo=1000; % Number of Monte Carlo simulations 
MC_mode='B'; % Monte Carlo simulation mode ('E' to randomise earthquake dates, 'V' to randomise volcanic eruption dates, 'B' to randomise both, 'P' for purmutation test (shuffle dates))

home_dir= 'C:\Users\ex18983\eqvolc github'; % Home directory for function


% CALCULATION

% Switch to home directory
cd(home_dir)

% Convert to MATLAB date formats
start_datenum=datenum(start_date,'dd/mm/yyyy');
end_datenum=datenum(end_date,'dd/mm/yyyy');

% Extract the desired earthquake events from the earthquake catalogue
[inpeqs,noinpeqs]=geteq(DB_inpeqs,lonlims,latlims,start_datenum,end_datenum,minEQ,maxEQ,mindepth,maxdepth,sliptype,fashockcheck,fashockdist);

% Extract the desired volcanic eruptions from the eruptions catalogue
[inpvolcs,noinpvolcs]=getvolc(lonlims,latlims,start_datenum,end_datenum,minVEI,DB_inperups,uncert_erups);

% Extract start and end years of dataset
start_year=str2double(start_date(end-3:end));
end_year=str2double(end_date(end-3:end));
% Generate vector of year bins
xyears=start_year:1:end_year;

% Generate vector of yearly bin boundary dates (1st Jan xxxx) 
datebounds=zeros(1,size(xyears,2));
no_years=size(datebounds,2)-1;
% Fill in boundary date numbers
for i=start_year:end_year
    datebounds(i-start_year+1)=datenum(strcat('01/01/',num2str(i)),'dd/mm/yyyy'); % Alter these to experiment shifting boundaries?
end

% Remove final boundary date for timeseries 
xyears=xyears(1:end-1);

% Assign the real earthquakes and eruptions to their correct bins
[eqs,volcs,seismoment]=bineqvolcs(no_years,datebounds,inpeqs,noinpeqs,inpvolcs,noinpvolcs,mult_erups,vmode);

% If applicable, begin Monte Carlo simulation
if monte_carlo>0
    
    % Preallocate arrays to store the monte_carlo outputs. Each row is one
    % monte carlo simulation
    eqsMC=zeros(monte_carlo,no_years);
    volcsMC=zeros(monte_carlo,no_years);
    seismomentMC=zeros(monte_carlo,no_years);
    
    % Begin Monte Carlo simulation loop
    for i=1:monte_carlo
        
        % Randomise the appropriate variables (-1 because end date is day
        % after last day of records)
        if MC_mode=='E'
            for j=1:noinpeqs
                inpeqs{j,1}=round(end_datenum-1-rand*(end_datenum-1-start_datenum));
            end
        elseif MC_mode=='V'
            for j=1:noinpvolcs
                inpvolcs{j,3}=round(end_datenum-1-rand*(end_datenum-1-start_datenum));
            end
        elseif MC_mode=='B'
            for j=1:noinpeqs
                inpeqs{j,1}=round(end_datenum-1-rand*(end_datenum-1-start_datenum));
            end
            for j=1:noinpvolcs
                inpvolcs{j,3}=round(end_datenum-1-rand*(end_datenum-1-start_datenum));
            end
        elseif MC_mode=='P'
            alldates=zeros(noinpeqs+noinpvolcs,1);
            for j=1:noinpeqs
                alldates(j)=inpeqs{j,1};
            end
            for j=1:noinpvolcs
                alldates(noinpeqs+j)=inpvolcs{j,3};
            end
            alldates=alldates(randperm(length(alldates)));
            for j=1:noinpeqs
                inpeqs{j,1}=alldates(j);
            end
            for j=1:noinpvolcs
                inpvolcs{j,3}=alldates(noinpeqs+j);
            end
        end
        
        % Assign the MC earthquakes and eruptions to their correct bins
        [eqsMC(i,:),volcsMC(i,:),seismomentMC(i,:)]=bineqvolcs(no_years,datebounds,inpeqs,noinpeqs,inpvolcs,noinpvolcs,mult_erups,vmode);
    end
end

% Write output file, close all
overwr='Y';
cd('outputs')
[overwr]=overwrite_check(output_name,overwr);
if overwr=='Y'
    if monte_carlo==0
        save(output_name,'xyears','eqs','volcs','seismoment')
    else
        save(output_name,'xyears','eqs','volcs','seismoment','eqsMC','volcsMC','seismomentMC')
    end
end
fclose('all');

% Return to home
cd(home_dir)

end