function PlotTriggering3

% Plots eruption rates associated with large nearby earthquakes, using .mat
% file generated by EruptionTriggering.m

% This function makes plots for one set of input parameters (Min Mw,
% SlipType, MultErups, MaxD, etc), and one time period either before or
% after earthquakes, showing the proportion of individual earthquakes with
% given relative eruption rates. Also further divides the earthquakes by
% characteristics (mw, depth, slip orientation). Also calculates
% percentiles relative to any randomsied Monte Carlo simulations

% Figure 1 - Bar chart showing the proporition of earthquakes with a given
%            eruption rate, as a function of earthquake characteristic
% Figure 3 - Bar chart showing the proporition of earthquakes with a given
%            eruption rate, as a function of earthquake depth2
% Figure 4 - Bar chart showing the proporition of earthquakes with a given
%            post-earthquake eruption rate, as a function of pre-earthquake
%            eruption rate
% Figure 5 - Bar chart showing the proporition of earthquakes with a given
%            post-earthquake eruption rate, as a function of pre-earthquake
%            eruption rate and earthquake characteristic combined
% Figure 6 - Scatter plot of relative pre-earthquake eruption rate against
%            relative post-earthquake eruption rate for each earthquake
%            near an active volcano


% INPUT

% Input file (only 1 set of parameters and time period, so only 1 file)
inp_file = 'ET_test_1year';

% Calculations and plots for eruption rates before or after earthquakes?
ba = 'B'; % 'A' for after; 'B' for before

% Threshold relative eruption rates for two bins (First is the maximum
% rate for low rates bin, second is the minimum rate for high rates bin)
thresh = [1 1]; % [Maximum value for low bin   Minimum value for high bin]

% Earthquake characteristic values to divide by
depth = 70; % Depth cut-off for depth groups (1 value for 2 groups)
depth3 = [15 70 300]; % % Maximum depth values for second depth groups (3 values for 4 groups)
slipdepth = 70; % Maximum earthquake depth for dividing by slip orientation

% Home directory for function:
home_dir= 'C:\Users\ex18983\eqvolc github';


% CALCULATION

% Switch to home directory
cd(home_dir)

% Load the input file
load(inp_file);

% Determine numbers of simulations
if exist('E_beforeMC','var')
    no_MCs = size(E_beforeMC,1);
else
    no_MCs = 0;
end

% Calculate relative eruption rates per earthquake (1 row = 1 earthquake)
delta_Bavg_ind = E_before_byeq ./ E_average_byeq;
delta_Aavg_ind = E_after_byeq ./ E_average_byeq;

% Calculate simulated eruption rates per eartquake (rows = simulations,
% cols = earthquakes)
if no_MCs > 0
    delta_BavgMC_ind = E_beforeMC_byeq ./ E_averageMC_byeq;
    delta_AavgMC_ind = E_afterMC_byeq ./ E_averageMC_byeq;
end

% Convert NaN values created by earthquakes not near any active
% volcanoes (M=0) to 1 relative rate
delta_Bavg_ind(isnan(delta_Bavg_ind)) = 1;
delta_Aavg_ind(isnan(delta_Aavg_ind)) = 1;
if no_MCs > 0
    delta_BavgMC_ind(isnan(delta_BavgMC_ind)) = 1;
    delta_AavgMC_ind(isnan(delta_AavgMC_ind)) = 1;
end

% Pre-allocate arrays to store percentile scores for each earthquake
noeqs = length(E_after_byeq);

% Preallocate arrays for earthquake characteristics (counts number of
% earthquakes with each characteristic)
% For all earthquakes near eruptions:
eqdepth_all = zeros(1,2); % Depth 2 groups
eqdepth3_all = zeros(1,4); % Depth 4 groups
eqtype_all = zeros(1,4); % Shallow slip type: Reverse, normal, strike-slip, other
eqerupsbefore_all = zeros(1,2); % Eruptions in same time period before: Below average, above average
% For earthquakes with eruption rates in ba in first bin (<thresh(1)):
eqdepth_low = zeros(1,2);
eqdepth3_low = zeros(1,4);
eqtype_low = zeros(1,4);
eqerupsbefore_low = zeros(1,2);
% For earthquakes with above rates in ba in second bin (>thresh(2)):
eqdepth_high = zeros(1,2);
eqdepth3_high = zeros(1,4);
eqtype_high = zeros(1,4);
eqerupsbefore_high = zeros(1,2);
% If ba = a, combination of earthquakes by characteristic and
% pre-earthquake eruption rate (counts number of earthquakes with each
% combination of characteristic and pre-earthquake eruption rate): 
%All earthquakes near eruptions:
deeperupsbefore_all = zeros(1,2); % All deep earthquakes: below average pre earthquake rate, above average pre-earthquake rate
shallowerupsbefore_all = zeros(1,2);
reverseerupsbefore_all = zeros(1,2);
normalerupsbefore_all = zeros(1,2);
sserupsbefore_all = zeros(1,2);
% Earthquakes with low post-earthquake eruption rate:
deeperupsbefore_low = zeros(1,2); % Deep earthquakes with below average post earthquake rate: below average pre earthquake rate, above average pre-earthquake rate
shallowerupsbefore_low = zeros(1,2);
reverseerupsbefore_low = zeros(1,2);
normalerupsbefore_low = zeros(1,2);
sserupsbefore_low = zeros(1,2);
% Earthquakes with high post-earthquake eruption rate:
deeperupsbefore_high = zeros(1,2); % Deep earthquakes with above average post earthquake rate: below average pre earthquake rate, above average pre-earthquake rate
shallowerupsbefore_high = zeros(1,2);
reverseerupsbefore_high = zeros(1,2);
normalerupsbefore_high = zeros(1,2);
sserupsbefore_high = zeros(1,2);

% Simulations characteristcis (same as above but 1 row per simulation)
no_MC = length(E_averageMC);
MCeqdepth_all = zeros(no_MC,2); % Depth 2 groups
MCeqdepth3_all = zeros(no_MC,4); % Depth 4 groups
MCeqtype_all = zeros(no_MC,4); % Shallow slip type: Reverse, normal, strike-slip, other
MCeqerupsbefore_all = zeros(no_MC,2); % Eruptions in same time period before: Below average, above average
MCeqdepth_low = zeros(no_MC,2);
MCeqdepth3_low = zeros(no_MC,4);
MCeqtype_low = zeros(no_MC,4);
MCeqerupsbefore_low = zeros(no_MC,2);
MCeqdepth_high = zeros(no_MC,2);
MCeqdepth3_high = zeros(no_MC,4);
MCeqtype_high = zeros(no_MC,4);
MCeqerupsbefore_high = zeros(no_MC,2);
MCdeeperupsbefore_all = zeros(no_MC,2); % All deep earthquakes below average pre earthquake rate, above average pre-earthquake rate
MCshallowerupsbefore_all = zeros(no_MC,2);
MCreverseerupsbefore_all = zeros(no_MC,2);
MCnormalerupsbefore_all = zeros(no_MC,2);
MCsserupsbefore_all = zeros(no_MC,2);
MCdeeperupsbefore_low = zeros(no_MC,2); % Deep earthquakes with below average post earthquake rate: below average pre earthquake rate, above average pre-earthquake rate
MCshallowerupsbefore_low = zeros(no_MC,2);
MCreverseerupsbefore_low = zeros(no_MC,2);
MCnormalerupsbefore_low = zeros(no_MC,2);
MCsserupsbefore_low = zeros(no_MC,2);
MCdeeperupsbefore_high = zeros(no_MC,2);  % Deep earthquakes with above average post earthquake rate: below average pre earthquake rate, above average pre-earthquake rate
MCshallowerupsbefore_high = zeros(no_MC,2);
MCreverseerupsbefore_high = zeros(no_MC,2);
MCnormalerupsbefore_high = zeros(no_MC,2);
MCsserupsbefore_high = zeros(no_MC,2);

% Numbers of earthquakes near active volcanoes counter
noeqs_nrvolcs = 0;

% Calculate characteristics of all earthquakes near eruptions
for i = 1 : noeqs
    % Check if earthquake is near an active volcano
    if E_average_byeq(i) > 0 || E_before_byeq(i) > 0 || E_after_byeq(i) > 0
        
        % Add to counter
        noeqs_nrvolcs = noeqs_nrvolcs + 1;
      
        % Determine if interested in rate change before or after
        % Before
        if ba == 'B'
            
            % Add characteristics to the characteristics for all
            % earthquakes near active volcanoes bin
            % Depth
            if triggers{i,1}{4} >= depth
                eqdepth_all(2) = eqdepth_all(2) + 1;
            else
                eqdepth_all(1) = eqdepth_all(1) + 1;
            end
            % Depth 3
            if triggers{i,1}{4} < depth3(1)
                eqdepth3_all(1) = eqdepth3_all(1) + 1;
            elseif triggers{i,1}{4} < depth3(2)
                eqdepth3_all(2) = eqdepth3_all(2) + 1;
            elseif triggers{i,1}{4} < depth3(3)
                eqdepth3_all(3) = eqdepth3_all(3) + 1;
            else
                eqdepth3_all(4) = eqdepth3_all(4) + 1;
            end
            % Slip type
            if strcmp(triggers{i,1}{7},'reverse') && triggers{i,1}{4} < slipdepth
                eqtype_all(1) = eqtype_all(1) + 1;
            elseif strcmp(triggers{i,1}{7},'normal') && triggers{i,1}{4} < slipdepth
                eqtype_all(2) = eqtype_all(2) + 1;
            elseif strcmp(triggers{i,1}{7},'strike-slip') && triggers{i,1}{4} < slipdepth
                eqtype_all(3) = eqtype_all(3) + 1;
            elseif triggers{i,1}{4} < slipdepth
                eqtype_all(4) = eqtype_all(4) + 1;
            end
            
            % Earthquake falls into the low bin
            if delta_Bavg_ind(i) < thresh(1)
                % Depth
                if triggers{i,1}{4} >= depth
                    eqdepth_low(2) = eqdepth_low(2) + 1;
                else
                    eqdepth_low(1) = eqdepth_low(1) + 1;
                end
                % Depth 3
                if triggers{i,1}{4} < depth3(1)
                    eqdepth3_low(1) = eqdepth3_low(1) + 1;
                elseif triggers{i,1}{4} < depth3(2)
                    eqdepth3_low(2) = eqdepth3_low(2) + 1;
                elseif triggers{i,1}{4} < depth3(3)
                    eqdepth3_low(3) = eqdepth3_low(3) + 1;
                else
                    eqdepth3_low(4) = eqdepth3_low(4) + 1;
                end
                % Slip type
                if strcmp(triggers{i,1}{7},'reverse') && triggers{i,1}{4} < slipdepth
                    eqtype_low(1) = eqtype_low(1) + 1;
                elseif strcmp(triggers{i,1}{7},'normal') && triggers{i,1}{4} < slipdepth
                    eqtype_low(2) = eqtype_low(2) + 1;
                elseif strcmp(triggers{i,1}{7},'strike-slip') && triggers{i,1}{4} < slipdepth
                    eqtype_low(3) = eqtype_low(3) + 1;
                elseif triggers{i,1}{4} < slipdepth
                    eqtype_low(4) = eqtype_low(4) + 1;
                end
            end
            
            % Earthquake falls into the high bin
            if delta_Bavg_ind(i) > thresh(2)
                % Depth
                if triggers{i,1}{4} >= depth
                    eqdepth_high(2) = eqdepth_high(2) + 1;
                else
                    eqdepth_high(1) = eqdepth_high(1) + 1;
                end
                % Depth 3
                if triggers{i,1}{4} < depth3(1)
                    eqdepth3_high(1) = eqdepth3_high(1) + 1;
                elseif triggers{i,1}{4} < depth3(2)
                    eqdepth3_high(2) = eqdepth3_high(2) + 1;
                elseif triggers{i,1}{4} < depth3(3)
                    eqdepth3_high(3) = eqdepth3_high(3) + 1;
                else
                    eqdepth3_high(4) = eqdepth3_high(4) + 1;
                end
                % Slip type
                if strcmp(triggers{i,1}{7},'reverse') && triggers{i,1}{4} < slipdepth
                    eqtype_high(1) = eqtype_high(1) + 1; 
                elseif strcmp(triggers{i,1}{7},'normal') && triggers{i,1}{4} < slipdepth
                    eqtype_high(2) = eqtype_high(2) + 1;
                elseif strcmp(triggers{i,1}{7},'strike-slip') && triggers{i,1}{4} < slipdepth
                    eqtype_high(3) = eqtype_high(3) + 1;
                elseif triggers{i,1}{4} < slipdepth
                    eqtype_high(4) = eqtype_high(4) + 1;
                end
            end
            
        % After
        elseif ba == 'A'
            
            % Add characteristics to the characteristics for all
            % earthquakes near active volcanoes bin
            % Depth
            if triggers{i,1}{4} >= depth
                eqdepth_all(2) = eqdepth_all(2) + 1;
            else
                eqdepth_all(1) = eqdepth_all(1) + 1;
            end
            % Depth 3
            if triggers{i,1}{4} < depth3(1)
                eqdepth3_all(1) = eqdepth3_all(1) + 1;
            elseif triggers{i,1}{4} < depth3(2)
                eqdepth3_all(2) = eqdepth3_all(2) + 1;
            elseif triggers{i,1}{4} < depth3(3)
                eqdepth3_all(3) = eqdepth3_all(3) + 1;
            else
                eqdepth3_all(4) = eqdepth3_all(4) + 1;
            end
            % Slip type
            if strcmp(triggers{i,1}{7},'reverse') && triggers{i,1}{4} < slipdepth
                eqtype_all(1) = eqtype_all(1) + 1;
            elseif strcmp(triggers{i,1}{7},'normal') && triggers{i,1}{4} < slipdepth
                eqtype_all(2) = eqtype_all(2) + 1;
            elseif strcmp(triggers{i,1}{7},'strike-slip') && triggers{i,1}{4} < slipdepth
                eqtype_all(3) = eqtype_all(3) + 1;
            elseif triggers{i,1}{4} < slipdepth
                eqtype_all(4) = eqtype_all(4) + 1;
            end
            % Eruptions before below avg
            if delta_Bavg_ind(i) < 1
                eqerupsbefore_all(1) = eqerupsbefore_all(1) + 1;
                % Eruptions before by type
                % Depth
                if triggers{i,1}{4} >= depth
                    deeperupsbefore_all(1) = deeperupsbefore_all(1) + 1;
                else
                    shallowerupsbefore_all(1) = shallowerupsbefore_all(1) + 1;
                end
                % Slip tpye
                if strcmp(triggers{i,1}{7},'reverse') && triggers{i,1}{4} < slipdepth
                    reverseerupsbefore_all(1) = reverseerupsbefore_all(1) + 1;
                elseif strcmp(triggers{i,1}{7},'normal') && triggers{i,1}{4} < slipdepth
                    normalerupsbefore_all(1) = normalerupsbefore_all(1) + 1;
                elseif strcmp(triggers{i,1}{7},'strike-slip') && triggers{i,1}{4} < slipdepth
                    sserupsbefore_all(1) = sserupsbefore_all(1) + 1;
                end
            % Eruption before above avg
            elseif delta_Bavg_ind(i) > 1
                eqerupsbefore_all(2) = eqerupsbefore_all(2) + 1;
                % Eruptions before by type
                % Depth
                if triggers{i,1}{4} >= depth
                    deeperupsbefore_all(2) = deeperupsbefore_all(2) + 1;
                else
                    shallowerupsbefore_all(2) = shallowerupsbefore_all(2) + 1;
                end
                % Slip tpye
                if strcmp(triggers{i,1}{7},'reverse') && triggers{i,1}{4} < slipdepth
                    reverseerupsbefore_all(2) = reverseerupsbefore_all(2) + 1;
                elseif strcmp(triggers{i,1}{7},'normal') && triggers{i,1}{4} < slipdepth
                    normalerupsbefore_all(2) = normalerupsbefore_all(2) + 1;
                elseif strcmp(triggers{i,1}{7},'strike-slip') && triggers{i,1}{4} < slipdepth
                    sserupsbefore_all(2) = sserupsbefore_all(2) + 1;
                end
            end
            
            % Earthquake falls into the low bin
            if delta_Aavg_ind(i) < thresh(1)
                % Depth
                if triggers{i,1}{4} >= depth
                    eqdepth_low(2) = eqdepth_low(2) + 1;
                else
                    eqdepth_low(1) = eqdepth_low(1) + 1;
                end
                % Depth 3
                if triggers{i,1}{4} < depth3(1)
                    eqdepth3_low(1) = eqdepth3_low(1) + 1;
                elseif triggers{i,1}{4} < depth3(2)
                    eqdepth3_low(2) = eqdepth3_low(2) + 1;
                elseif triggers{i,1}{4} < depth3(3)
                    eqdepth3_low(3) = eqdepth3_low(3) + 1;
                else
                    eqdepth3_low(4) = eqdepth3_low(4) + 1;
                end
                % Slip type
                if strcmp(triggers{i,1}{7},'reverse') && triggers{i,1}{4} < slipdepth
                    eqtype_low(1) = eqtype_low(1) + 1;
                elseif strcmp(triggers{i,1}{7},'normal') && triggers{i,1}{4} < slipdepth
                    eqtype_low(2) = eqtype_low(2) + 1;
                elseif strcmp(triggers{i,1}{7},'strike-slip') && triggers{i,1}{4} < slipdepth
                    eqtype_low(3) = eqtype_low(3) + 1;
                elseif triggers{i,1}{4} < slipdepth
                    eqtype_low(4) = eqtype_low(4) + 1;
                end
                % Eruptions before below avg
                if delta_Bavg_ind(i) < 1
                    eqerupsbefore_low(1) = eqerupsbefore_low(1) + 1;
                    % Eruptions before by type
                    % Depth
                    if triggers{i,1}{4} >= depth
                        deeperupsbefore_low(1) = deeperupsbefore_low(1) + 1;
                    else
                        shallowerupsbefore_low(1) = shallowerupsbefore_low(1) + 1;
                    end
                    % Slip tpye
                    if strcmp(triggers{i,1}{7},'reverse') && triggers{i,1}{4} < slipdepth
                        reverseerupsbefore_low(1) = reverseerupsbefore_low(1) + 1;
                    elseif strcmp(triggers{i,1}{7},'normal') && triggers{i,1}{4} < slipdepth
                        normalerupsbefore_low(1) = normalerupsbefore_low(1) + 1;
                    elseif strcmp(triggers{i,1}{7},'strike-slip') && triggers{i,1}{4} < slipdepth
                        sserupsbefore_low(1) = sserupsbefore_low(1) + 1;
                    end
                % Eruptions before above avg
                elseif delta_Bavg_ind(i) > 1
                    eqerupsbefore_low(2) = eqerupsbefore_low(2) + 1;
                    % Eruptions before by type
                    % Depth
                    if triggers{i,1}{4} >= depth
                        deeperupsbefore_low(2) = deeperupsbefore_low(2) + 1;
                    else
                        shallowerupsbefore_low(2) = shallowerupsbefore_low(2) + 1;
                    end
                    % Slip tpye
                    if strcmp(triggers{i,1}{7},'reverse') && triggers{i,1}{4} < slipdepth
                        reverseerupsbefore_low(2) = reverseerupsbefore_low(2) + 1;
                    elseif strcmp(triggers{i,1}{7},'normal') && triggers{i,1}{4} < slipdepth
                        normalerupsbefore_low(2) = normalerupsbefore_low(2) + 1;
                    elseif strcmp(triggers{i,1}{7},'strike-slip') && triggers{i,1}{4} < slipdepth
                        sserupsbefore_low(2) = sserupsbefore_low(2) + 1;
                    end
                end
            end
            
            % Earthquake falls into the high bin
            if delta_Aavg_ind(i) > thresh(2)
                % Depth
                if triggers{i,1}{4} >= depth
                    eqdepth_high(2) = eqdepth_high(2) + 1;
                else
                    eqdepth_high(1) = eqdepth_high(1) + 1;
                end
                % Depth 3
                if triggers{i,1}{4} < depth3(1)
                    eqdepth3_high(1) = eqdepth3_high(1) + 1;
                elseif triggers{i,1}{4} < depth3(2)
                    eqdepth3_high(2) = eqdepth3_high(2) + 1;
                elseif triggers{i,1}{4} < depth3(3)
                    eqdepth3_high(3) = eqdepth3_high(3) + 1;
                else
                    eqdepth3_high(4) = eqdepth3_high(4) + 1;
                end
                % Slip type
                if strcmp(triggers{i,1}{7},'reverse') && triggers{i,1}{4} < slipdepth
                    eqtype_high(1) = eqtype_high(1) + 1;
                elseif strcmp(triggers{i,1}{7},'normal') && triggers{i,1}{4} < slipdepth
                    eqtype_high(2) = eqtype_high(2) + 1;
                elseif strcmp(triggers{i,1}{7},'strike-slip') && triggers{i,1}{4} < slipdepth
                    eqtype_high(3) = eqtype_high(3) + 1;
                elseif triggers{i,1}{4} < slipdepth
                    eqtype_high(4) = eqtype_high(4) + 1;
                end
                % Eruptions before below avg
                if delta_Bavg_ind(i) < 1
                    eqerupsbefore_high(1) = eqerupsbefore_high(1) + 1;
                    % Eruptions before by type
                    % Depth
                    if triggers{i,1}{4} >= depth
                        deeperupsbefore_high(1) = deeperupsbefore_high(1) + 1;
                    else
                        shallowerupsbefore_high(1) = shallowerupsbefore_high(1) + 1;
                    end
                    % Slip tpye
                    if strcmp(triggers{i,1}{7},'reverse') && triggers{i,1}{4} < slipdepth
                        reverseerupsbefore_high(1) = reverseerupsbefore_high(1) + 1;
                    elseif strcmp(triggers{i,1}{7},'normal') && triggers{i,1}{4} < slipdepth
                        normalerupsbefore_high(1) = normalerupsbefore_high(1) + 1;
                    elseif strcmp(triggers{i,1}{7},'strike-slip') && triggers{i,1}{4} < slipdepth
                        sserupsbefore_high(1) = sserupsbefore_high(1) + 1;
                    end
                % Eruptions before above avg
                elseif delta_Bavg_ind(i) > 1
                    eqerupsbefore_high(2) = eqerupsbefore_high(2) + 1;
                    % Eruptions before by type
                    % Depth
                    if triggers{i,1}{4} >= depth
                        deeperupsbefore_high(2) = deeperupsbefore_high(2) + 1;
                    else
                        shallowerupsbefore_high(2) = shallowerupsbefore_high(2) + 1;
                    end
                    % Slip tpye
                    if strcmp(triggers{i,1}{7},'reverse') && triggers{i,1}{4} < slipdepth
                        reverseerupsbefore_high(2) = reverseerupsbefore_high(2) + 1;
                    elseif strcmp(triggers{i,1}{7},'normal') && triggers{i,1}{4} < slipdepth
                        normalerupsbefore_high(2) = normalerupsbefore_high(2) + 1;
                    elseif strcmp(triggers{i,1}{7},'strike-slip') && triggers{i,1}{4} < slipdepth
                        sserupsbefore_high(2) = sserupsbefore_high(2) + 1;
                    end
                end
            end
        end
    end
end

% Calculate characteristics of all earthquakes near eruptions for
% simulations
for t = 1 : no_MC
    for i = 1 : noeqs
        % Check if earthquake is near an active volcano
        if E_averageMC_byeq(t,i) > 0 || E_beforeMC_byeq(t,i) > 0 || E_afterMC_byeq(t,i) > 0
            
            % Determine if interested in rate change before or after
            % Before
            if ba == 'B'
                
                % Add characteristics to the characteristics for all
                % earthquakes near active volcanoes bin
                % Depth
                if triggers{i,1}{4} >= depth
                    MCeqdepth_all(t,2) = MCeqdepth_all(t,2) + 1;
                else
                    MCeqdepth_all(t,1) = MCeqdepth_all(t,1) + 1;
                end
                % Depth 3
                if triggers{i,1}{4} < depth3(1)
                    MCeqdepth3_all(t,1) = MCeqdepth3_all(t,1) + 1;
                elseif triggers{i,1}{4} < depth3(2)
                    MCeqdepth3_all(t,2) = MCeqdepth3_all(t,2) + 1;
                elseif triggers{i,1}{4} < depth3(3)
                    MCeqdepth3_all(t,3) = MCeqdepth3_all(t,3) + 1;
                else
                    MCeqdepth3_all(t,4) = MCeqdepth3_all(t,4) + 1;
                end
                % Slip type
                if strcmp(triggers{i,1}{7},'reverse') && triggers{i,1}{4} < slipdepth
                    MCeqtype_all(t,1) = MCeqtype_all(t,1) + 1;
                elseif strcmp(triggers{i,1}{7},'normal') && triggers{i,1}{4} < slipdepth
                    MCeqtype_all(t,2) = MCeqtype_all(t,2) + 1;
                elseif strcmp(triggers{i,1}{7},'strike-slip') && triggers{i,1}{4} < slipdepth
                    MCeqtype_all(t,3) = MCeqtype_all(t,3) + 1;
                elseif triggers{i,1}{4} < slipdepth
                    MCeqtype_all(t,4) = MCeqtype_all(t,4) + 1;
                end
                
                % Earthquake falls into the low bin
                if delta_BavgMC_ind(t,i) < thresh(1)
                    % Depth
                    if triggers{i,1}{4} >= depth
                        MCeqdepth_low(t,2) = MCeqdepth_low(t,2) + 1;
                    else
                        MCeqdepth_low(t,1) = MCeqdepth_low(t,1) + 1;
                    end
                    % Depth 3
                    if triggers{i,1}{4} < depth3(1)
                        MCeqdepth3_low(t,1) = MCeqdepth3_low(t,1) + 1;
                    elseif triggers{i,1}{4} < depth3(2)
                        MCeqdepth3_low(t,2) = MCeqdepth3_low(t,2) + 1;
                    elseif triggers{i,1}{4} < depth3(3)
                        MCeqdepth3_low(t,3) = MCeqdepth3_low(t,3) + 1;
                    else
                        MCeqdepth3_low(t,4) = MCeqdepth3_low(t,4) + 1;
                    end
                    % Slip type
                    if strcmp(triggers{i,1}{7},'reverse') && triggers{i,1}{4} < slipdepth
                        MCeqtype_low(t,1) = MCeqtype_low(t,1) + 1;
                    elseif strcmp(triggers{i,1}{7},'normal') && triggers{i,1}{4} < slipdepth
                        MCeqtype_low(t,2) = MCeqtype_low(t,2) + 1;
                    elseif strcmp(triggers{i,1}{7},'strike-slip') && triggers{i,1}{4} < slipdepth
                        MCeqtype_low(t,3) = MCeqtype_low(t,3) + 1;
                    elseif triggers{i,1}{4} < slipdepth
                        MCeqtype_low(t,4) = MCeqtype_low(t,4) + 1;
                    end
                end
                
                % Earthquake falls into the high bin
                if delta_BavgMC_ind(t,i) > thresh(2)
                    % Depth
                    if triggers{i,1}{4} >= depth
                        MCeqdepth_high(t,2) = MCeqdepth_high(t,2) + 1;
                    else
                        MCeqdepth_high(t,1) = MCeqdepth_high(t,1) + 1;
                    end
                    % Depth 3
                    if triggers{i,1}{4} < depth3(1)
                        MCeqdepth3_high(t,1) = MCeqdepth3_high(t,1) + 1;
                    elseif triggers{i,1}{4} < depth3(2)
                        MCeqdepth3_high(t,2) = MCeqdepth3_high(t,2) + 1;
                    elseif triggers{i,1}{4} < depth3(3)
                        MCeqdepth3_high(t,3) = MCeqdepth3_high(t,3) + 1;
                    else
                        MCeqdepth3_high(t,4) = MCeqdepth3_high(t,4) + 1;
                    end
                    % Slip type
                    if strcmp(triggers{i,1}{7},'reverse') && triggers{i,1}{4} < slipdepth
                        MCeqtype_high(t,1) = MCeqtype_high(t,1) + 1;
                    elseif strcmp(triggers{i,1}{7},'normal') && triggers{i,1}{4} < slipdepth
                        MCeqtype_high(t,2) = MCeqtype_high(t,2) + 1;
                    elseif strcmp(triggers{i,1}{7},'strike-slip') && triggers{i,1}{4} < slipdepth
                        MCeqtype_high(t,3) = MCeqtype_high(t,3) + 1;
                    elseif triggers{i,1}{4} < slipdepth
                        MCeqtype_high(t,4) = MCeqtype_high(t,4) + 1;
                    end
                end
                
                % After
            elseif ba == 'A'
                
                % Add characteristics to the characteristics for all
                % earthquakes near active volcanoes bin
                % Depth
                if triggers{i,1}{4} >= depth
                    MCeqdepth_all(t,2) = MCeqdepth_all(t,2) + 1;
                else
                    MCeqdepth_all(t,1) = MCeqdepth_all(t,1) + 1;
                end
                % Depth 3
                if triggers{i,1}{4} < depth3(1)
                    MCeqdepth3_all(t,1) = MCeqdepth3_all(t,1) + 1;
                elseif triggers{i,1}{4} < depth3(2)
                    MCeqdepth3_all(t,2) = MCeqdepth3_all(t,2) + 1;
                elseif triggers{i,1}{4} < depth3(3)
                    MCeqdepth3_all(t,3) = MCeqdepth3_all(t,3) + 1;
                else
                    MCeqdepth3_all(t,4) = MCeqdepth3_all(t,4) + 1;
                end
                % Slip type
                if strcmp(triggers{i,1}{7},'reverse') && triggers{i,1}{4} < slipdepth
                    MCeqtype_all(t,1) = MCeqtype_all(t,1) + 1;
                elseif strcmp(triggers{i,1}{7},'normal') && triggers{i,1}{4} < slipdepth
                    MCeqtype_all(t,2) = MCeqtype_all(t,2) + 1;
                elseif strcmp(triggers{i,1}{7},'strike-slip') && triggers{i,1}{4} < slipdepth
                    MCeqtype_all(t,3) = MCeqtype_all(t,3) + 1;
                elseif triggers{i,1}{4} < slipdepth
                    MCeqtype_all(t,4) = MCeqtype_all(t,4) + 1;
                end
                % Eruptions before below avg
                if delta_BavgMC_ind(t,i) < 1
                    MCeqerupsbefore_all(t,1) = MCeqerupsbefore_all(t,1) + 1;
                    % Eruptions before by type
                    % Depth
                    if triggers{i,1}{4} >= depth
                        MCdeeperupsbefore_all(t,1) = MCdeeperupsbefore_all(t,1) + 1;
                    else
                        MCshallowerupsbefore_all(t,1) = MCshallowerupsbefore_all(t,1) + 1;
                    end
                    % Slip tpye
                    if strcmp(triggers{i,1}{7},'reverse') && triggers{i,1}{4} < slipdepth
                        MCreverseerupsbefore_all(t,1) = MCreverseerupsbefore_all(t,1) + 1;
                    elseif strcmp(triggers{i,1}{7},'normal') && triggers{i,1}{4} < slipdepth
                        MCnormalerupsbefore_all(t,1) = MCnormalerupsbefore_all(t,1) + 1;
                    elseif strcmp(triggers{i,1}{7},'strike-slip') && triggers{i,1}{4} < slipdepth
                        MCsserupsbefore_all(t,1) = MCsserupsbefore_all(t,1) + 1;
                    end
                % Eruption before above avg
                elseif delta_BavgMC_ind(t,i) > 1
                    MCeqerupsbefore_all(t,2) = MCeqerupsbefore_all(t,2) + 1;
                    % Eruptions before by type
                    % Depth
                    if triggers{i,1}{4} >= depth
                        MCdeeperupsbefore_all(t,2) = MCdeeperupsbefore_all(t,2) + 1;
                    else
                        MCshallowerupsbefore_all(t,2) = MCshallowerupsbefore_all(t,2) + 1;
                    end
                    % Slip tpye
                    if strcmp(triggers{i,1}{7},'reverse') && triggers{i,1}{4} < slipdepth
                        MCreverseerupsbefore_all(t,2) = MCreverseerupsbefore_all(t,2) + 1;
                    elseif strcmp(triggers{i,1}{7},'normal') && triggers{i,1}{4} < slipdepth
                        MCnormalerupsbefore_all(t,2) = MCnormalerupsbefore_all(t,2) + 1;
                    elseif strcmp(triggers{i,1}{7},'strike-slip') && triggers{i,1}{4} < slipdepth
                        MCsserupsbefore_all(t,2) = MCsserupsbefore_all(t,2) + 1;
                    end
                end
                
                % Earthquake falls into the low bin
                if delta_AavgMC_ind(t,i) < thresh(1)
                    % Depth
                    if triggers{i,1}{4} >= depth
                        MCeqdepth_low(t,2) = MCeqdepth_low(t,2) + 1;
                    else
                        MCeqdepth_low(t,1) = MCeqdepth_low(t,1) + 1;
                    end
                    % Depth 3
                    if triggers{i,1}{4} < depth3(1)
                        MCeqdepth3_low(t,1) = MCeqdepth3_low(t,1) + 1;
                    elseif triggers{i,1}{4} < depth3(2)
                        MCeqdepth3_low(t,2) = MCeqdepth3_low(t,2) + 1;
                    elseif triggers{i,1}{4} < depth3(3)
                        MCeqdepth3_low(t,3) = MCeqdepth3_low(t,3) + 1;
                    else
                        MCeqdepth3_low(t,4) = MCeqdepth3_low(t,4) + 1;
                    end
                    % Slip type
                    if strcmp(triggers{i,1}{7},'reverse') && triggers{i,1}{4} < slipdepth
                        MCeqtype_low(t,1) = MCeqtype_low(t,1) + 1;
                    elseif strcmp(triggers{i,1}{7},'normal') && triggers{i,1}{4} < slipdepth
                        MCeqtype_low(t,2) = MCeqtype_low(t,2) + 1;
                    elseif strcmp(triggers{i,1}{7},'strike-slip') && triggers{i,1}{4} < slipdepth
                        MCeqtype_low(t,3) = MCeqtype_low(t,3) + 1;
                    elseif triggers{i,1}{4} < slipdepth
                        MCeqtype_low(t,4) = MCeqtype_low(t,4) + 1;
                    end
                    % Eruptions before below avg
                    if delta_BavgMC_ind(t,i) < 1
                        MCeqerupsbefore_low(t,1) = MCeqerupsbefore_low(t,1) + 1;
                        % Eruptions before by type
                        % Depth
                        if triggers{i,1}{4} >= depth
                            MCdeeperupsbefore_low(t,1) = MCdeeperupsbefore_low(t,1) + 1;
                        else
                            MCshallowerupsbefore_low(t,1) = MCshallowerupsbefore_low(t,1) + 1;
                        end
                        % Slip tpye
                        if strcmp(triggers{i,1}{7},'reverse') && triggers{i,1}{4} < slipdepth
                            MCreverseerupsbefore_low(t,1) = MCreverseerupsbefore_low(t,1) + 1;
                        elseif strcmp(triggers{i,1}{7},'normal') && triggers{i,1}{4} < slipdepth
                            MCnormalerupsbefore_low(t,1) = MCnormalerupsbefore_low(t,1) + 1;
                        elseif strcmp(triggers{i,1}{7},'strike-slip') && triggers{i,1}{4} < slipdepth
                            MCsserupsbefore_low(t,1) = MCsserupsbefore_low(t,1) + 1;
                        end
                        % Eruptions before above avg
                    elseif delta_BavgMC_ind(t,i) > 1
                        MCeqerupsbefore_low(t,2) = MCeqerupsbefore_low(t,2) + 1;
                        % Eruptions before by type
                        % Depth
                        if triggers{i,1}{4} >= depth
                            MCdeeperupsbefore_low(t,2) = MCdeeperupsbefore_low(t,2) + 1;
                        else
                            MCshallowerupsbefore_low(t,2) = MCshallowerupsbefore_low(t,2) + 1;
                        end
                        % Slip tpye
                        if strcmp(triggers{i,1}{7},'reverse') && triggers{i,1}{4} < slipdepth
                            MCreverseerupsbefore_low(t,2) = MCreverseerupsbefore_low(t,2) + 1;
                        elseif strcmp(triggers{i,1}{7},'normal') && triggers{i,1}{4} < slipdepth
                            MCnormalerupsbefore_low(t,2) = MCnormalerupsbefore_low(t,2) + 1;
                        elseif strcmp(triggers{i,1}{7},'strike-slip') && triggers{i,1}{4} < slipdepth
                            MCsserupsbefore_low(t,2) = MCsserupsbefore_low(t,2) + 1;
                        end
                    end
                end
                
                % Earthquake falls into the high bin
                if delta_AavgMC_ind(t,i) > thresh(2)
                    % Depth
                    if triggers{i,1}{4} >= depth
                        MCeqdepth_high(t,2) = MCeqdepth_high(t,2) + 1;
                    else
                        MCeqdepth_high(t,1) = MCeqdepth_high(t,1) + 1;
                    end
                    % Depth 3
                    if triggers{i,1}{4} < depth3(1)
                        MCeqdepth3_high(t,1) = MCeqdepth3_high(t,1) + 1;
                    elseif triggers{i,1}{4} < depth3(2)
                        MCeqdepth3_high(t,2) = MCeqdepth3_high(t,2) + 1;
                    elseif triggers{i,1}{4} < depth3(3)
                        MCeqdepth3_high(t,3) = MCeqdepth3_high(t,3) + 1;
                    else
                        MCeqdepth3_high(t,4) = MCeqdepth3_high(t,4) + 1;
                    end
                    % Slip type
                    if strcmp(triggers{i,1}{7},'reverse') && triggers{i,1}{4} < slipdepth
                        MCeqtype_high(t,1) = MCeqtype_high(t,1) + 1;
                    elseif strcmp(triggers{i,1}{7},'normal') && triggers{i,1}{4} < slipdepth
                        MCeqtype_high(t,2) = MCeqtype_high(t,2) + 1;
                    elseif strcmp(triggers{i,1}{7},'strike-slip') && triggers{i,1}{4} < slipdepth
                        MCeqtype_high(t,3) = MCeqtype_high(t,3) + 1;
                    elseif triggers{i,1}{4} < slipdepth
                        MCeqtype_high(t,4) = MCeqtype_high(t,4) + 1;
                    end
                    % Eruptions before below avg
                    if delta_BavgMC_ind(t,i) < 1
                        MCeqerupsbefore_high(t,1) = MCeqerupsbefore_high(t,1) + 1;
                        % Eruptions before by type
                        % Depth
                        if triggers{i,1}{4} >= depth
                            MCdeeperupsbefore_high(t,1) = MCdeeperupsbefore_high(t,1) + 1;
                        else
                            MCshallowerupsbefore_high(t,1) = MCshallowerupsbefore_high(t,1) + 1;
                        end
                        % Slip tpye
                        if strcmp(triggers{i,1}{7},'reverse') && triggers{i,1}{4} < slipdepth
                            MCreverseerupsbefore_high(t,1) = MCreverseerupsbefore_high(t,1) + 1;
                        elseif strcmp(triggers{i,1}{7},'normal') && triggers{i,1}{4} < slipdepth
                            MCnormalerupsbefore_high(t,1) = MCnormalerupsbefore_high(t,1) + 1;
                        elseif strcmp(triggers{i,1}{7},'strike-slip') && triggers{i,1}{4} < slipdepth
                            MCsserupsbefore_high(t,1) = MCsserupsbefore_high(t,1) + 1;
                        end
                        % Eruptions before above avg
                    elseif delta_BavgMC_ind(t,i) > 1
                        MCeqerupsbefore_high(t,2) = MCeqerupsbefore_high(t,2) + 1;
                        % Eruptions before by type
                        % Depth
                        if triggers{i,1}{4} >= depth
                            MCdeeperupsbefore_high(t,2) = MCdeeperupsbefore_high(t,2) + 1;
                        else
                            MCshallowerupsbefore_high(t,2) = MCshallowerupsbefore_high(t,2) + 1;
                        end
                        % Slip tpye
                        if strcmp(triggers{i,1}{7},'reverse') && triggers{i,1}{4} < slipdepth
                            MCreverseerupsbefore_high(t,2) = MCreverseerupsbefore_high(t,2) + 1;
                        elseif strcmp(triggers{i,1}{7},'normal') && triggers{i,1}{4} < slipdepth
                            MCnormalerupsbefore_high(t,2) = MCnormalerupsbefore_high(t,2) + 1;
                        elseif strcmp(triggers{i,1}{7},'strike-slip') && triggers{i,1}{4} < slipdepth
                            MCsserupsbefore_high(t,2) = MCsserupsbefore_high(t,2) + 1;
                        end
                    end
                end
            end
        end
    end
end

% For each characteristic, determine number of earthquakes producing each
% given rate change [low rate change   other   high rate change]
deep = [eqdepth_low(2) (eqdepth_all(2)-eqdepth_low(2)-eqdepth_high(2)) eqdepth_high(2)];
shallow = [eqdepth_low(1) (eqdepth_all(1)-eqdepth_low(1)-eqdepth_high(1)) eqdepth_high(1)];
l15 = [eqdepth3_low(1) (eqdepth3_all(1)-eqdepth3_low(1)-eqdepth3_high(1)) eqdepth3_high(1)];
g15l70 = [eqdepth3_low(2) (eqdepth3_all(2)-eqdepth3_low(2)-eqdepth3_high(2)) eqdepth3_high(2)];
g70l300 = [eqdepth3_low(3) (eqdepth3_all(3)-eqdepth3_low(3)-eqdepth3_high(3)) eqdepth3_high(3)];
g300 = [eqdepth3_low(4) (eqdepth3_all(4)-eqdepth3_low(4)-eqdepth3_high(4)) eqdepth3_high(4)];
reverse = [eqtype_low(1) (eqtype_all(1)-eqtype_low(1)-eqtype_high(1)) eqtype_high(1)];
normal = [eqtype_low(2) (eqtype_all(2)-eqtype_low(2)-eqtype_high(2)) eqtype_high(2)];
ss = [eqtype_low(3) (eqtype_all(3)-eqtype_low(3)-eqtype_high(3)) eqtype_high(3)];
lowbefore = [eqerupsbefore_low(1) (eqerupsbefore_all(1)-eqerupsbefore_low(1)-eqerupsbefore_high(1)) eqerupsbefore_high(1)];
highbefore = [eqerupsbefore_low(2) (eqerupsbefore_all(2)-eqerupsbefore_low(2)-eqerupsbefore_high(2)) eqerupsbefore_high(2)];
lowdeepbefore = [deeperupsbefore_low(1) (deeperupsbefore_all(1)-deeperupsbefore_low(1)-deeperupsbefore_high(1)) deeperupsbefore_high(1)];
highdeepbefore = [deeperupsbefore_low(2) (deeperupsbefore_all(2)-deeperupsbefore_low(2)-deeperupsbefore_high(2)) deeperupsbefore_high(2)];
lowshallowbefore = [shallowerupsbefore_low(1) (shallowerupsbefore_all(1)-shallowerupsbefore_low(1)-shallowerupsbefore_high(1)) shallowerupsbefore_high(1)];
highshallowbefore = [shallowerupsbefore_low(2) (shallowerupsbefore_all(2)-shallowerupsbefore_low(2)-shallowerupsbefore_high(2)) shallowerupsbefore_high(2)];
lowreversebefore = [reverseerupsbefore_low(1) (reverseerupsbefore_all(1)-reverseerupsbefore_low(1)-reverseerupsbefore_high(1)) reverseerupsbefore_high(1)];
highreversebefore = [reverseerupsbefore_low(2) (reverseerupsbefore_all(2)-reverseerupsbefore_low(2)-reverseerupsbefore_high(2)) reverseerupsbefore_high(2)];
lownormalbefore = [normalerupsbefore_low(1) (normalerupsbefore_all(1)-normalerupsbefore_low(1)-normalerupsbefore_high(1)) normalerupsbefore_high(1)];
highnormalbefore = [normalerupsbefore_low(2) (normalerupsbefore_all(2)-normalerupsbefore_low(2)-normalerupsbefore_high(2)) normalerupsbefore_high(2)];
lowssbefore = [sserupsbefore_low(1) (sserupsbefore_all(1)-sserupsbefore_low(1)-sserupsbefore_high(1)) sserupsbefore_high(1)];
highssbefore = [sserupsbefore_low(2) (sserupsbefore_all(2)-sserupsbefore_low(2)-sserupsbefore_high(2)) sserupsbefore_high(2)];

% For each characteristic, determine number of earthquakes producing each
% given rate change [low rate change   other   high rate change] -
% simultions
if no_MCs > 0
    MCdeep = [MCeqdepth_low(:,2) (MCeqdepth_all(:,2)-MCeqdepth_low(:,2)-MCeqdepth_high(:,2)) MCeqdepth_high(:,2)];
    MCshallow = [MCeqdepth_low(:,1) (MCeqdepth_all(:,1)-MCeqdepth_low(:,1)-MCeqdepth_high(:,1)) MCeqdepth_high(:,1)];
    MCl15 = [MCeqdepth3_low(:,1) (MCeqdepth3_all(:,1)-MCeqdepth3_low(:,1)-MCeqdepth3_high(:,1)) MCeqdepth3_high(:,1)];
    MCg15l70 = [MCeqdepth3_low(:,2) (MCeqdepth3_all(:,2)-MCeqdepth3_low(:,2)-MCeqdepth3_high(:,2)) MCeqdepth3_high(:,2)];
    MCg70l300 = [MCeqdepth3_low(:,3) (MCeqdepth3_all(:,3)-MCeqdepth3_low(:,3)-MCeqdepth3_high(:,3)) MCeqdepth3_high(:,3)];
    MCg300 = [MCeqdepth3_low(:,4) (MCeqdepth3_all(:,4)-MCeqdepth3_low(:,4)-MCeqdepth3_high(:,4)) MCeqdepth3_high(:,4)];
    MCreverse = [MCeqtype_low(:,1) (MCeqtype_all(:,1)-MCeqtype_low(:,1)-MCeqtype_high(:,1)) MCeqtype_high(:,1)];
    MCnormal = [MCeqtype_low(:,2) (MCeqtype_all(:,2)-MCeqtype_low(:,2)-MCeqtype_high(:,2)) MCeqtype_high(:,2)];
    MCss = [MCeqtype_low(:,3) (MCeqtype_all(:,3)-MCeqtype_low(:,3)-MCeqtype_high(:,3)) MCeqtype_high(:,3)];
    MClowbefore = [MCeqerupsbefore_low(:,1) (MCeqerupsbefore_all(:,1)-MCeqerupsbefore_low(:,1)-MCeqerupsbefore_high(:,1)) MCeqerupsbefore_high(:,1)];
    MChighbefore = [MCeqerupsbefore_low(:,2) (MCeqerupsbefore_all(:,2)-MCeqerupsbefore_low(:,2)-MCeqerupsbefore_high(:,2)) MCeqerupsbefore_high(:,2)];
    MClowdeepbefore = [MCdeeperupsbefore_low(:,1) (MCdeeperupsbefore_all(:,1)-MCdeeperupsbefore_low(:,1)-MCdeeperupsbefore_high(:,1)) MCdeeperupsbefore_high(:,1)];
    MChighdeepbefore = [MCdeeperupsbefore_low(:,2) (MCdeeperupsbefore_all(:,2)-MCdeeperupsbefore_low(:,2)-deeperupsbefore_high(:,2)) MCdeeperupsbefore_high(:,2)];
    MClowshallowbefore = [MCshallowerupsbefore_low(:,1) (MCshallowerupsbefore_all(:,1)-MCshallowerupsbefore_low(:,1)-MCshallowerupsbefore_high(:,1)) MCshallowerupsbefore_high(:,1)];
    MChighshallowbefore = [MCshallowerupsbefore_low(:,2) (MCshallowerupsbefore_all(:,2)-MCshallowerupsbefore_low(:,2)-MCshallowerupsbefore_high(:,2)) MCshallowerupsbefore_high(:,2)];
    MClowreversebefore = [MCreverseerupsbefore_low(:,1) (MCreverseerupsbefore_all(:,1)-MCreverseerupsbefore_low(:,1)-MCreverseerupsbefore_high(:,1)) MCreverseerupsbefore_high(:,1)];
    MChighreversebefore = [MCreverseerupsbefore_low(:,2) (MCreverseerupsbefore_all(:,2)-MCreverseerupsbefore_low(:,2)-MCreverseerupsbefore_high(:,2)) MCreverseerupsbefore_high(:,2)];
    MClownormalbefore = [MCnormalerupsbefore_low(:,1) (MCnormalerupsbefore_all(:,1)-MCnormalerupsbefore_low(:,1)-MCnormalerupsbefore_high(:,1)) MCnormalerupsbefore_high(:,1)];
    MChighnormalbefore = [MCnormalerupsbefore_low(:,2) (MCnormalerupsbefore_all(:,2)-MCnormalerupsbefore_low(:,2)-MCnormalerupsbefore_high(:,2)) MCnormalerupsbefore_high(:,2)];
    MClowssbefore = [MCsserupsbefore_low(:,1) (MCsserupsbefore_all(:,1)-MCsserupsbefore_low(:,1)-MCsserupsbefore_high(:,1)) MCsserupsbefore_high(:,1)];
    MChighssbefore = [MCsserupsbefore_low(:,2) (MCsserupsbefore_all(:,2)-MCsserupsbefore_low(:,2)-MCsserupsbefore_high(:,2)) MCsserupsbefore_high(:,2)];
end

% Normalise by numbers of eqs with each characteristic
deep = deep / sum(deep);
shallow = shallow / sum(shallow);
l15 = l15 / sum(l15);
g15l70 = g15l70 / sum(g15l70);
g70l300 = g70l300 / sum(g70l300);
g300 = g300 / sum(g300);
reverse = reverse / sum(reverse);
normal = normal / sum(normal);
ss = ss / sum(ss);
lowbefore = lowbefore / sum(lowbefore);
highbefore = highbefore/ sum(highbefore);
lowdeepbefore = lowdeepbefore / sum(lowdeepbefore);
highdeepbefore = highdeepbefore / sum(highdeepbefore);
lowshallowbefore = lowshallowbefore / sum(lowshallowbefore);
highshallowbefore = highshallowbefore / sum(highshallowbefore);
lowreversebefore = lowreversebefore / sum(lowreversebefore);
highreversebefore = highreversebefore / sum(highreversebefore);
lownormalbefore = lownormalbefore / sum(lownormalbefore);
highnormalbefore = highnormalbefore / sum(highnormalbefore);
lowssbefore = lowssbefore / sum(lowssbefore);
highssbefore = highssbefore / sum(highssbefore);
% Normalise by numbers of eqs with each characteristic - simulations
if no_MCs > 0
    MCdeep = MCdeep ./ sum(MCdeep,2);
    MCshallow = MCshallow ./ sum(MCshallow,2);
    MCl15 = MCl15 ./ sum(MCl15);
    MCg15l70 = MCg15l70 ./ sum(MCg15l70);
    MCg70l300 = MCg70l300 ./ sum(MCg70l300);
    MCg300 = MCg300 ./ sum(MCg300);
    MCreverse = MCreverse ./ sum(MCreverse,2);
    MCnormal = MCnormal ./ sum(MCnormal,2);
    MCss = MCss ./ sum(MCss,2);
    MClowbefore = MClowbefore ./ sum(MClowbefore,2);
    MChighbefore = MChighbefore ./ sum(MChighbefore,2);
    MClowdeepbefore = MClowdeepbefore ./ sum(MClowdeepbefore,2);
    MChighdeepbefore = MChighdeepbefore ./ sum(MChighdeepbefore,2);
    MClowshallowbefore = MClowshallowbefore ./ sum(MClowshallowbefore,2);
    MChighshallowbefore = MChighshallowbefore ./ sum(MChighshallowbefore,2);
    MClowreversebefore = MClowreversebefore ./ sum(MClowreversebefore,2);
    MChighreversebefore = MChighreversebefore ./ sum(MChighreversebefore,2);
    MClownormalbefore = MClownormalbefore ./ sum(MClownormalbefore,2);
    MChighnormalbefore = MChighnormalbefore ./ sum(MChighnormalbefore,2);
    MClowssbefore = MClowssbefore ./ sum(MClowssbefore,2);
    MChighssbefore = MChighssbefore ./ sum(MChighssbefore,2);
end

% Concact arrays for better bar charts
combi = [deep; shallow; reverse; normal; ss];
depth2 = [l15; g15l70; g70l300; g300];
beforecombi = [lowbefore; highbefore];
deepbefore = [lowdeepbefore; highdeepbefore];
shallowbefore = [lowshallowbefore; highshallowbefore];
reversebefore = [lowreversebefore; highreversebefore];
normalbefore = [lownormalbefore; highnormalbefore];
ssbefore = [lowssbefore; highssbefore];

% Calculate percentiles relative to simulations (percentiles only
% calculated for the second (greater than rate) bin)
if no_MCs > 0
    [Pdeepmin,Pdeepmed,Pdeepmax] = alexinvprctile(MCdeep(:,3),deep(3));
    [Pshallowmin,Pshallowmed,Pshallowmax] = alexinvprctile(MCshallow(:,3),shallow(3));
    [Preversemin,Preversemed,Preversemax] = alexinvprctile(MCreverse(:,3),reverse(3));
    [Pnormalmin,Pnormalmed,Pnormalmax] = alexinvprctile(MCnormal(:,3),normal(3));
    [Pssmin,Pssmed,Pssmax] = alexinvprctile(MCss(:,3),ss(3));
    [Pl15min,Pl15med,Pl15max] = alexinvprctile(MCl15(:,3),l15(3));
    [Pg15l70min,Pg15l70med,Pg15l70max] = alexinvprctile(MCg15l70(:,3),g15l70(3));
    [Pg70l300min,Pg70l300med,Pg70l300max] = alexinvprctile(MCg70l300(:,3),g70l300(3));
    [Pg300min,Pg300med,Pg300max] = alexinvprctile(MCg300(:,3),g300(3));
    [Plowbeforemin,Plowbeforemed,Plowbeforemax] = alexinvprctile(MClowbefore(:,3),lowbefore(3));
    [Phighbeforemin,Phighbeforemed,Phighbeforemax] = alexinvprctile(MChighbefore(:,3),highbefore(3));
    [Plowdeepbeforemin,Plowdeepbeforemed,Plowdeepbeforemax] = alexinvprctile(MClowdeepbefore(:,3),lowdeepbefore(3));
    [Phighdeepbeforemin,Phighdeepbeforemed,Phighdeepbeforemax] = alexinvprctile(MChighdeepbefore(:,3),highdeepbefore(3));
    [Plowshallowbeforemin,Plowshallowbeforemed,Plowshallowbeforemax] = alexinvprctile(MClowshallowbefore(:,3),lowshallowbefore(3));
    [Phighshallowbeforemin,Phighshallowbeforemed,Phighshallowbeforemax] = alexinvprctile(MChighshallowbefore(:,3),highshallowbefore(3));
    [Plowreversebeforemin,Plowreversebeforemed,Plowreversebeforemax] = alexinvprctile(MClowreversebefore(:,3),lowreversebefore(3));
    [Phighreversebeforemin,Phighreversebeforemed,Phighreversebeforemax] = alexinvprctile(MChighreversebefore(:,3),highreversebefore(3));
    [Plownormalbeforemin,Plownormalbeforemed,Plownormalbeforemax] = alexinvprctile(MClownormalbefore(:,3),lownormalbefore(3));
    [Phighnormalbeforemin,Phighnormalbeforemed,Phighnormalbeforemax] = alexinvprctile(MChighnormalbefore(:,3),highnormalbefore(3));
    [Plowssbeforemin,Plowssbeforemed,Plowssbeforemax] = alexinvprctile(MClowssbefore(:,3),lowssbefore(3));
    [Phighssbeforemin,Phighssbeforemed,Phighssbeforemax] = alexinvprctile(MChighssbefore(:,3),highssbefore(3));
end

% Labels for bar charts
combilabel = categorical({'Deep','Shallow','Shallow reverse','Shallow normal','Shallow strike-slip'});
combilabel = reordercats(combilabel,{'Deep','Shallow','Shallow reverse','Shallow normal','Shallow strike-slip'});
depthlabel2 = categorical({strcat('<',num2str(depth3(1)),' km'),strcat(num2str(depth3(1)),'-',num2str(depth3(2)),' km'),strcat(num2str(depth3(2)),'-',num2str(depth3(3)),' km'),strcat('>',num2str(depth3(3)),' km')});
depthlabel2 = reordercats(depthlabel2,{strcat('<',num2str(depth3(1)),' km'),strcat(num2str(depth3(1)),'-',num2str(depth3(2)),' km'),strcat(num2str(depth3(2)),'-',num2str(depth3(3)),' km'),strcat('>',num2str(depth3(3)),' km')});
if ba == 'A'
    bclabel = categorical({'\Delta B < 0','\Delta B > 0'});
    bclabel = reordercats(bclabel,{'\Delta B < 0','\Delta B > 0'});
end

% Better bar chart of characteristics 
a=figure(1);
a.Units = 'normalized';
a.Position = [0 0.2083 0.7495 0.5833];
bar(combilabel,combi,'stacked')
xlabel('Earthquake classification')
if ba == 'B'
    ylabel('Proportion of earthquakes: f(B)')
elseif ba == 'A'
    ylabel('Proportion of earthquakes: f(A)')
end
if ba == 'B'
    if thresh(2) == thresh(1)
        legend(strcat('\Delta B < ',num2str(thresh(1))),'',strcat('\Delta B > ',num2str(thresh(2))))
    else
        legend(strcat('\Delta B < ',num2str(thresh(1))),'Other',strcat('\Delta B > ',num2str(thresh(2))))
    end
elseif ba == 'A'
    if thresh(2) == thresh(1)
        legend(strcat('\Delta A < ',num2str(thresh(1))),'',strcat('\Delta A > ',num2str(thresh(2))))
    else
        legend(strcat('\Delta A < ',num2str(thresh(1))),'Other',strcat('\Delta A > ',num2str(thresh(2))))
    end
end
a1=gca;
a1.Position = [0.1300 0.1192 0.7750 0.8058];
a1.FontSize=12;
a1.LineWidth=0.75;
a1.YTick=[0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1];

% Bar chart of depths2
y=figure(3);
y.Units = 'normalized';
y.Position = [0 0.2083 0.7495 0.5833];
bar(depthlabel2,depth2,'stacked')
xlabel('Earthquake depth')
if ba == 'B'
    ylabel('Proportion of earthquakes: f(B)')
elseif ba == 'A'
    ylabel('Proportion of earthquakes: f(A)')
end
if ba == 'B'
    if thresh(2) == thresh(1)
        legend(strcat('\Delta B < ',num2str(thresh(1))),'',strcat('\Delta B > ',num2str(thresh(2))))
    else
        legend(strcat('\Delta B < ',num2str(thresh(1))),'Other',strcat('\Delta B > ',num2str(thresh(2))))
    end
elseif ba == 'A'
    if thresh(2) == thresh(1)
        legend(strcat('\Delta A < ',num2str(thresh(1))),'',strcat('\Delta A > ',num2str(thresh(2))))
    else
        legend(strcat('\Delta A < ',num2str(thresh(1))),'Other',strcat('\Delta A > ',num2str(thresh(2))))
    end
end
a1=gca;
a1.Position = [0.1300 0.1192 0.7750 0.8058];
a1.FontSize=12;
a1.LineWidth=0.75;
a1.YTick=[0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1];

if ba == 'A'
    % Bar chart of rate before
    b=figure(4);
    b.Units = 'normalized';
    b.Position = [0 0.2083 0.7495 0.5833];
    bar(bclabel,beforecombi,'stacked')
    xlabel('1 year pre-earthquake eruption rate variation')
    if ba == 'B'
        ylabel('Proportion of earthquakes: f(B)')
    elseif ba == 'A'
        ylabel('Proportion of earthquakes: f(A)')
    end
    if thresh(2) == thresh(1)
        legend(strcat('\Delta A < ',num2str(thresh(1))),'',strcat('\Delta A > ',num2str(thresh(2))))
    else
        legend(strcat('\Delta A < ',num2str(thresh(1))),'Other',strcat('\Delta A > ',num2str(thresh(2))))
    end
    b1=gca;
    b1.Position = [0.1300 0.1192 0.7750 0.8058];
    b1.FontSize=12;
    b1.LineWidth=0.75;
    b1.YTick=[0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1];
    
    % Better bar chart of rates before and charactertsics combined
    d=figure(5);
    d.Units = 'normalized';
    d.Position = [0 0.2083 0.7495 0.5833];
    subplot(1,5,1)
    bar(bclabel,deepbefore,'stacked')
    xlabel('Deep')
    if ba == 'B'
        ylabel('Proportion of earthquakes: f(B)')
    elseif ba == 'A'
        ylabel('Proportion of earthquakes: f(A)')
    end
    d1=gca;
    d1.FontSize=12;
    d1.LineWidth=0.75;
    d1.YTick=[0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1];
    if thresh(2) == thresh(1)
        legend(strcat('\Delta A < ',num2str(thresh(1))),'',strcat('\Delta A > ',num2str(thresh(2))))
    else
        legend(strcat('\Delta A < ',num2str(thresh(1))),'Other',strcat('\Delta A > ',num2str(thresh(2))))
    end
    subplot(1,5,2)
    bar(bclabel,shallowbefore,'stacked')
    xlabel('Shallow')
    d2=gca;
    d2.FontSize=12;
    d2.LineWidth=0.75;
    d2.YTick=[0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1];
    subplot(1,5,3)
    bar(bclabel,reversebefore,'stacked')
    xlabel('Shallow reverse')
    d3=gca;
    d3.FontSize=12;
    d3.LineWidth=0.75;
    d3.YTick=[0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1];
    subplot(1,5,4)
    bar(bclabel,normalbefore,'stacked')
    xlabel('Shallow normal')
    d4=gca;
    d4.FontSize=12;
    d4.LineWidth=0.75;
    d4.YTick=[0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1];
    subplot(1,5,5)
    bar(bclabel,ssbefore,'stacked')
    xlabel('Shallow strike-slip')
    d5=gca;
    d5.FontSize=12;
    d5.LineWidth=0.75;
    d5.YTick=[0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1];
end

% Plot a scatter of before vs after rates for earthquakes near volcanoes
pl_delta_Bavg_ind = zeros(1,noeqs_nrvolcs);
pl_delta_Aavg_ind = pl_delta_Bavg_ind;
j = 1; % counter
% Log for plotting
for i = 1 : noeqs
    % Check if earthquake is near an active volcano
    if E_average_byeq(i) > 0 || E_before_byeq(i) > 0 || E_after_byeq(i) > 0
        if delta_Bavg_ind(i) == 0
            pl_delta_Bavg_ind(j) = -1; % Spoof value for 0 relative eruption rate to plot where it should on log scale 
        else
            pl_delta_Bavg_ind(j) = log10(delta_Bavg_ind(i));
        end
        if delta_Aavg_ind(i) == 0
            pl_delta_Aavg_ind(j) = -1; % Spoof value for 0 relative eruption rate to plot where it should on log scale 
        else
            pl_delta_Aavg_ind(j) = log10(delta_Aavg_ind(i));
        end
        j = j + 1;
    end
end
% Calculate number in each quadrant
noquad = zeros(1,4); % both neg, B neg A pos, both pos, B pos A neg
for i = 1 : noeqs_nrvolcs
    if pl_delta_Bavg_ind(i) < 1 && pl_delta_Aavg_ind(i) < 1
        noquad(1) = noquad(1)+1;
    elseif pl_delta_Bavg_ind(i) < 1 && pl_delta_Aavg_ind(i) > 1
        noquad(2) = noquad(2)+1;
    elseif pl_delta_Bavg_ind(i) > 1 && pl_delta_Aavg_ind(i) > 1
        noquad(3) = noquad(3)+1;
    elseif pl_delta_Bavg_ind(i) > 1 && pl_delta_Aavg_ind(i) < 1
        noquad(4) = noquad(4)+1;
    end
end
% PLot before vs after
c=figure(6);
c.Units = 'normalized';
c.Position = [0 0.2083 0.4375 0.5833];
hold off
scatter(pl_delta_Bavg_ind,pl_delta_Aavg_ind,36,'o')
xlabel('\Delta B_i')
ylabel('\Delta A_i')
hold on
plot([0 0],[-5 5],'k')
plot([-5 5],[0 0],'k')
plot([-5 5],[-5 5],'k--')
c1=gca;
c1.XLim=([-1 2]);
c1.YLim=([-1 2]);
c1.XTick=-1:1:2;
c1.YTick=-1:1:2;
c1.XTickLabel={'0','1','10','100'};
c1.YTickLabel={'0','1','10','100'};
c1.FontSize=12;
c1.LineWidth=0.75;

% Note about percentile scores
disp('NOTE: to view percentile scores relative to any randomised simulations for the proporition of earthquakes with given relative eruption rates, use a breakpoint at end of script and find the P scores in the workspace (or place pointer over variable names at line 883) (labelling bar charts is tricky!)')

end