function PlotTriggering

% Plots eruption rates associated with large nearby earthquakes, using .mat
% file generated by EruptionTriggering.m

% This function makes plots for one set of input parameters (Min Mw,
% SlipType, MultErups, MaxD, etc), but for different time periods before
% and after the earthquakes (Maxt), showing the observed relative eruption
% rates overlying the percentiles from any Monte Carlo simulations.

% Figure 1 - Before vs after eruption rates across all earthquakes
% Figure 2 - Before and after rates relative to baseline rate across all
%            earthquakes


% INPUT

% Cell array of input files. One column per time period, only one row as
% only one set of input parameters is permitted: 
% inp_files = {'ET_test_1month_noMC','ET_test_3month_noMC','ET_test_6month_noMC','ET_test_1year_noMC','ET_test_2year_noMC','ET_test_3year_noMC','ET_test_4year_noMC','ET_test_5year_noMC'};
inp_files = {'ET_test_1month','ET_test_3month','ET_test_6month','ET_test_1year','ET_test_2year','ET_test_3year','ET_test_4year','ET_test_5year'};

% Percentiles of MC simulation data to plot on figures:
pcts_plot = [1 10 32 50 68 90 99]; 
% Plot data labels ('Y' or 'N'):
labelling = 'Y'; 
% Time cumulatvie ('C' - points) or time bins ('B' - straight lines) input
meth = 'C'; 

% Home directory for function:
home_dir= 'C:\Users\ex18983\eqvolc github';


% CALCULATION

% Switch to home directory
cd(home_dir)

% Determine number of time periods
no_ts = size(inp_files,2);

% Load first input file
load(inp_files{1});

% Determine number of MC simulations (this should be the same for every
% input!) and number of percentiles to plot
if exist('E_beforeMC','var')
    no_MCs = size(E_beforeMC,1);
    no_pcts = size(pcts_plot,2);
else
    no_MCs = 0;
    no_pcts = 0;
end

% Pre-allocate arrays to store data
maxts = zeros(1,no_ts); % Time periods
E_befores = zeros(1,no_ts); % Number of observed eruptions before earthquakes
E_afters = zeros(1,no_ts); % Number of observed eruptions after earthquakes
E_averages = zeros(1,no_ts); % Average number of eruptions over time period
no_triggered = zeros(1,no_ts); % Number of excess eruptions after relative to before
no_triggeredBM = zeros(1,no_ts); % Number of excess eruptions before relative to mean
no_triggeredAM = zeros(1,no_ts); % Number of excess eruptions after relative to mean
delta_AB = zeros(1,no_ts); % Rate after earthquake relative to before
delta_ABMC = zeros(no_MCs,no_ts); % Simulared rate after earthquake relative to before
delta_Bavg = zeros(1,no_ts); % Rate before earthquake relative to average
delta_BavgMC = zeros(no_MCs,no_ts); % Simulated rate before earthquake relative to average
delta_Aavg = zeros(1,no_ts); % Rate after earthquake relative to average
delta_AavgMC = zeros(no_MCs,no_ts); % Simulated rate after earthquake relative to average
ABMC_pcts = zeros(no_pcts,no_ts); % Percentile values after earthquake relative to before
BavgMC_pcts = zeros(no_pcts,no_ts); % Percentile values before earthquake relative to average
AavgMC_pcts = zeros(no_pcts,no_ts); % Percentile values after earthquake relative to average
P_ABmin = zeros(1,no_ts); % Probability of non-exceedance after earthquake relative to before (Lower bound due to MC simulations with same value)
P_Bavgmin = zeros(1,no_ts); % Probability of non-exceedance before earthquake relative to average (Lower bound due to MC simulations with same value)
P_Aavgmin = zeros(1,no_ts); % Probability of non-exceedance after earthquake relative to average (Lower bound due to MC simulations with same value)
P_ABmax = zeros(1,no_ts); % Probability of non-exceedance after earthquake relative to before (Upper bound due to MC simulations with same value)
P_Bavgmax = zeros(1,no_ts); % Probability of non-exceedance before earthquake relative to average (Upper bound due to MC simulations with same value)
P_Aavgmax = zeros(1,no_ts); % Probability of non-exceedance after earthquake relative to average (Upper bound due to MC simulations with same value)

% Run loop extracting data and calculating rates
for i = 1 : no_ts
    
    % Load input file
    load(inp_files{i});
    
    % Extract time period for plotting
    maxts(i) = maxt;
    
    % Extract total eruption numbers and excess eruptions
    E_befores(i) = E_before;
    E_afters(i) = E_after;
    no_triggered(i) = E_after - E_before;
    no_triggeredBM(i) = E_before - E_average;
    no_triggeredAM(i) = E_after - E_average;
    E_averages(i) = E_average;
    
    % Calculate relative eruption rates
    delta_AB(i) = E_after / E_before;
    delta_Bavg(i) = E_before / E_average;
    delta_Aavg(i) = E_after / E_average;
    
    % Calculate simulated relative eruption rates 
    if no_MCs > 0
        delta_ABMC(:,i) = E_afterMC ./ E_beforeMC;
        delta_BavgMC(:,i) = E_beforeMC ./ E_averageMC;
        delta_AavgMC(:,i) = E_afterMC ./ E_averageMC;
    end
end

% Calculate MC percentiles for plotting
if no_pcts > 0
    for i = 1 : no_ts
        for j = 1 : no_pcts
            ABMC_pcts(j,i) = prctile(delta_ABMC(:,i),pcts_plot(j));
            BavgMC_pcts(j,i) = prctile(delta_BavgMC(:,i),pcts_plot(j));
            AavgMC_pcts(j,i) = prctile(delta_AavgMC(:,i),pcts_plot(j));
        end
    end
end

% Change Inf and Nan values for plotting and prctile calculation
pdelta_AB = delta_AB;
pdelta_AB(delta_AB==Inf) = 99999999999999999999999; % Replace to allow prctile calculation
pdelta_AB(isnan(delta_AB)) = -99999999999999999999999; % Replace to allow prctile calculation
if no_MCs > 0
    pdelta_ABMC = delta_ABMC;
    pdelta_ABMC(delta_ABMC==Inf) = 99999999999999999999999;
    pdelta_ABMC(isnan(delta_ABMC)) = -99999999999999999999999;
end

% Calculate probabilities of non-exceedance for observed data relative to
% MC simulations - upper bound (ie probability that observed <= MC)
if no_MCs > 0
    for i = 1 : no_ts
        [P_ABmin(i),~,P_ABmax(i)] = alexinvprctile(pdelta_ABMC(:,i),pdelta_AB(i));
        [P_Bavgmin(i),~,P_Bavgmax(i)] = alexinvprctile(delta_BavgMC(:,i),delta_Bavg(i));
        [P_Aavgmin(i),~,P_Aavgmax(i)] = alexinvprctile(delta_AavgMC(:,i),delta_Aavg(i));
    end
end

% Round probabilities and average rate for labelling
rdelta_AB = round(delta_AB,2);
rdelta_Bavg = round(delta_Bavg,2);
rdelta_Aavg = round(delta_Aavg,2);
E_averages = round(E_averages,1);
no_triggeredBM = round(no_triggeredBM,1);
no_triggeredAM = round(no_triggeredAM,1);
if no_MCs > 0
    P_ABmin = round(P_ABmin,1);
    P_Bavgmin = round(P_Bavgmin,1);
    P_Aavgmin = round(P_Aavgmin,1);
    P_ABmax = round(P_ABmax,1);
    P_Bavgmax = round(P_Bavgmax,1);
    P_Aavgmax = round(P_Aavgmax,1);
end

% Join before and after rates and significances for plotting
maxts_AB = [-flip(maxts) maxts];
delta_ABavg = [flip(delta_Bavg,2) delta_Aavg];
if no_MCs > 0
    ABavgMC_pcts = [flip(BavgMC_pcts,2) AavgMC_pcts];
end

% Plot figures
% Before vs after rate change
a=figure(1);
a.Units = 'normalized';
a.Position = [0 0.2083 0.7495 0.5833];
hold off
if meth == 'C'
    plot(maxts,delta_AB,'o-','LineWidth',1.33)
elseif meth == 'B'
    a = plot([0 maxts(1)],[delta_AB(1) delta_AB(1)]);
    a.Color = [0 0.4470 0.7410];
    a.LineWidth = 1.33;
    hold on
    for i = 1 : length(maxts)-1
        a = plot([maxts(i) maxts(i)],[delta_AB(i) delta_AB(i+1)]);
        a.Color = [0 0.4470 0.7410];
        a.LineWidth = 1.33;
        a.HandleVisibility = 'off';
        a = plot([maxts(i) maxts(i+1)],[delta_AB(i+1) delta_AB(i+1)]);
        a.Color = [0 0.4470 0.7410];
        a.LineWidth = 1.33;
        a.HandleVisibility = 'off';
    end
end
hold on
if no_pcts > 0
    for i = 1 : no_pcts
        if meth == 'C'
            plot(maxts,ABMC_pcts(i,:),'k--','LineWidth',0.75)
        elseif meth == 'B'
            a = plot([0 maxts(1)],[ABMC_pcts(i,1) ABMC_pcts(i,1)]);
            a.Color = 'k';
            a.LineStyle = '--';
            a.LineWidth = 0.75;
            hold on
            for j = 1 : length(maxts)-1
                a = plot([maxts(j) maxts(j)],[ABMC_pcts(i,j) ABMC_pcts(i,j+1)]);
                a.Color = 'k';
                a.LineStyle = '--';
                a.LineWidth = 0.75;
                a.HandleVisibility = 'off';
                a = plot([maxts(j) maxts(j+1)],[ABMC_pcts(i,j+1) ABMC_pcts(i,j+1)]);
                a.Color = 'k';
                a.LineStyle = '--';
                a.LineWidth = 0.75;
                a.HandleVisibility = 'off';
            end
        end
    end
end
xlabel('Time after earthquakes (days)')
ylabel({'Relative eruption rate'; '(\Delta A \\ \Delta B)'})
legend('Observed','Simulated percentiles','Location','southeast')
xlim([0 maxts(end)])
ylim([0 2]);
if labelling == 'Y'
    if no_pcts > 0
        for i = 1 : no_pcts
            text(((maxts(4)+maxts(3))/2),((ABMC_pcts(i,4)+ABMC_pcts(i,3))/2),num2str(pcts_plot(i)),'FontSize',11,'color','k')
        end
    end
%     for i = 1 : no_ts
%         text((maxts(1)+250+(i*150)),(0.7),{['t = ',num2str(maxts(i))],['\Delta = ',num2str(rdelta_AB(i))],['P = ',num2str(P_ABmin(i)),' - ',num2str(P_ABmax(i))],['B = ',num2str(E_befores(i))],['A = ',num2str(E_afters(i))],['T = ',num2str(no_triggered(i))]},'FontSize',10,'color','k')
%     end
end
a1=gca;
a1.Position = [0.1300 0.1192 0.7750 0.8058];
a1.FontSize=12;
a1.LineWidth=0.75;
a1.YTick = [0 0.2 0.4 0.6 0.8 1 1.2 1.4 1.6 1.8 2];
a1.XTick = [0 365 730 1096 1461 1826];
a1.XAxisLocation = 'bottom';
a1.YAxisLocation = 'left';

% Before and after relative to average rate change
b=figure(2);
b.Units = 'normalized';
b.Position = [0 0.2083 0.7495 0.5833];
hold off
if meth == 'C' 
    plot(maxts_AB,delta_ABavg,'o-','LineWidth',1.33)
elseif meth == 'B'
    a = plot([maxts_AB(1) maxts_AB(2)],[delta_ABavg(1) delta_ABavg(1)]);
    a.Color = [0 0.4470 0.7410];
    a.LineWidth = 1.33;
    hold on
    a = plot([maxts_AB(2) maxts_AB(2)],[delta_ABavg(1) delta_ABavg(2)]);
    a.Color = [0 0.4470 0.7410];
    a.LineWidth = 1.33;
    a.HandleVisibility = 'off';
    for i = 2 : length(maxts_AB)/2-1
        a = plot([maxts_AB(i) maxts_AB(i+1)],[delta_ABavg(i) delta_ABavg(i)]);
        a.Color = [0 0.4470 0.7410];
        a.LineWidth = 1.33;
        a.HandleVisibility = 'off';
        a = plot([maxts_AB(i+1) maxts_AB(i+1)],[delta_ABavg(i) delta_ABavg(i+1)]);
        a.Color = [0 0.4470 0.7410];
        a.LineWidth = 1.33;
        a.HandleVisibility = 'off';
    end   
    a = plot([maxts_AB(length(maxts_AB)/2) 0],[delta_ABavg(length(maxts_AB)/2) delta_ABavg(length(maxts_AB)/2)]);
    a.Color = [0 0.4470 0.7410];
    a.LineWidth = 1.33;
    a.HandleVisibility = 'off';
    a = plot([0 0],[delta_ABavg(length(maxts_AB)/2) delta_ABavg(1+length(maxts_AB)/2)]);
    a.Color = [0 0.4470 0.7410];
    a.LineWidth = 1.33;
    a.HandleVisibility = 'off';
    a = plot([0 maxts_AB(1+length(maxts_AB)/2)],[delta_ABavg(1+length(maxts_AB)/2) delta_ABavg(1+length(maxts_AB)/2)]);
    a.Color = [0 0.4470 0.7410];
    a.LineWidth = 1.33;
    a.HandleVisibility = 'off';
    for i = 1+length(maxts_AB)/2 : length(maxts_AB)-1
        a = plot([maxts_AB(i) maxts_AB(i)],[delta_ABavg(i) delta_ABavg(i+1)]);
        a.Color = [0 0.4470 0.7410];
        a.LineWidth = 1.33;
        a.HandleVisibility = 'off';
        a = plot([maxts_AB(i) maxts_AB(i+1)],[delta_ABavg(i+1) delta_ABavg(i+1)]);
        a.Color = [0 0.4470 0.7410];
        a.LineWidth = 1.33;
        a.HandleVisibility = 'off';
    end
end
hold on
if no_pcts > 0
    for i = 1 : no_pcts
        if meth == 'C'
            % Not joined up either side of 0 version:
            %plot(-maxts,BavgMC_pcts(i,:),'k--',maxts,AavgMC_pcts(i,:),'k--')
            % Joined either side of 0 version:
            plot(maxts_AB,ABavgMC_pcts(i,:),'k--','LineWidth',0.75)
        elseif meth == 'B'
            a = plot([maxts_AB(1) maxts_AB(2)],[ABavgMC_pcts(i,1) ABavgMC_pcts(i,1)]);
            a.Color = 'k';
            a.LineStyle = '--';
            a.LineWidth = 0.75;
            hold on
            a = plot([maxts_AB(2) maxts_AB(2)],[ABavgMC_pcts(i,1) ABavgMC_pcts(i,2)]);
            a.Color = 'k';
            a.LineStyle = '--';
            a.LineWidth = 0.75;
            a.HandleVisibility = 'off';
            for j = 2 : length(maxts_AB)/2-1
                a = plot([maxts_AB(j) maxts_AB(j+1)],[ABavgMC_pcts(i,j) ABavgMC_pcts(i,j)]);
                a.Color = 'k';
                a.LineStyle = '--';
                a.LineWidth = 0.75;
                a.HandleVisibility = 'off';
                a = plot([maxts_AB(j+1) maxts_AB(j+1)],[ABavgMC_pcts(i,j) ABavgMC_pcts(i,j+1)]);
                a.Color = 'k';
                a.LineStyle = '--';
                a.LineWidth = 0.75;
                a.HandleVisibility = 'off';
            end
            a = plot([maxts_AB(length(maxts_AB)/2) 0],[ABavgMC_pcts(i,length(maxts_AB)/2) ABavgMC_pcts(i,length(maxts_AB)/2)]);
            a.Color = 'k';
            a.LineStyle = '--';
            a.LineWidth = 0.75;
            a.HandleVisibility = 'off';
            a = plot([0 0],[ABavgMC_pcts(i,length(maxts_AB)/2) ABavgMC_pcts(i,1+length(maxts_AB)/2)]);
            a.Color = 'k';
            a.LineStyle = '--';
            a.LineWidth = 0.75;
            a.HandleVisibility = 'off';
            a = plot([0 maxts_AB(1+length(maxts_AB)/2)],[ABavgMC_pcts(i,1+length(maxts_AB)/2) ABavgMC_pcts(i,1+length(maxts_AB)/2)]);
            a.Color = 'k';
            a.LineStyle = '--';
            a.LineWidth = 0.75;
            a.HandleVisibility = 'off';
            for j = 1+length(maxts_AB)/2 : length(maxts_AB)-1
                a = plot([maxts_AB(j) maxts_AB(j)],[ABavgMC_pcts(i,j) ABavgMC_pcts(i,j+1)]);
                a.Color = 'k';
                a.LineStyle = '--';
                a.LineWidth = 0.75;
                a.HandleVisibility = 'off';
                a = plot([maxts_AB(j) maxts_AB(j+1)],[ABavgMC_pcts(i,j+1) ABavgMC_pcts(i,j+1)]);
                a.Color = 'k';
                a.LineStyle = '--';
                a.LineWidth = 0.75;
                a.HandleVisibility = 'off';
            end
        end
    end
    
end
xlabel('Time relative to earthquakes (days)')
ylabel({'Relative eruption rate'; '(\Delta (B,A))'})
legend('Observed','Simulated percentiles','Location','southeast')
xlim([-maxts(end) maxts(end)])
ylim([0 2]);
if labelling == 'Y'
    if no_pcts > 0
        for i = 1 : no_pcts
            text(((maxts(4)+maxts(3))/2),((AavgMC_pcts(i,4)+AavgMC_pcts(i,3))/2),num2str(pcts_plot(i)),'FontSize',11,'color','k')
            text(((-(maxts(4)+maxts(3))/2)),((BavgMC_pcts(i,4)+BavgMC_pcts(i,3))/2),num2str(pcts_plot(i)),'FontSize',11,'color','k')
        end
    end
%     for i = 1 : no_ts
%         text((maxts(1)-470+((i-1)*250)),(0.7),{['t = ',num2str(maxts(i))],['\Delta = ',num2str(rdelta_Aavg(i))],['P = ',num2str(P_Aavgmin(i)),' - ',num2str(P_Aavgmax(i))],['A = ',num2str(E_afters(i))],['M = ',num2str(E_averages(i))],['T = ',num2str(no_triggeredAM(i))]},'FontSize',10,'color','k')
%         text((maxts(1)+470-(i*250)),(-0.7),{['t = ',num2str(-maxts(i))],['\Delta = ',num2str(rdelta_Bavg(i))],['P = ',num2str(P_Bavgmin(i)),' - ',num2str(P_Bavgmax(i))],['B = ',num2str(E_befores(i))],['M = ',num2str(E_averages(i))],['T = ',num2str(no_triggeredBM(i))]},'FontSize',10,'color','k')
%     end
end
line([0 0],[-100 300],'Color',[0 0 0],'HandleVisibility','off')
b1=gca;
b1.Position = [0.1300 0.1192 0.7750 0.8058];
b1.FontSize=12;
b1.LineWidth=0.75;
b1.YTick = [0 0.2 0.4 0.6 0.8 1 1.2 1.4 1.6 1.8 2];
b1.XTick = [-1826 -1461 -1096 -730 -365 0 365 730 1096 1461 1826];
b1.XAxisLocation = 'bottom';
b1.YAxisLocation = 'left';

end